GET /api/readfile/1.txt HTTP/1.1
Host: 139.196.171.60:88
Accept-Language: zh-CN
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.100 Safari/537.36
Accept: */*
Referer: http://139.196.171.60:88/
Accept-Encoding: gzip, deflate, br
Connection: keep-alive

